"""Pytest configuration and fixtures."""

import random
import threading
import time
from typing import Generator

import pytest
import uvicorn

from .oauth_mock import app as oauth_app, PORT as OAUTH_PORT
from .app import make_app


class ServerThread(threading.Thread):
    # Generated by Claude

    def __init__(self, app, host, port):
        super().__init__(daemon=True)
        self.app = app
        self.host = host
        self.port = port
        self.server = None

    def run(self):
        """Run the uvicorn server."""
        config = uvicorn.Config(
            self.app,
            host=self.host,
            port=self.port,
            log_level="error",  # Suppress logs during tests
            access_log=False
        )
        self.server = uvicorn.Server(config)
        self.server.run()

    def stop(self):
        """Stop the server."""
        if self.server:
            self.server.should_exit = True


def create_endpoint(app, host, port):
    # Mostly generated by Claude

    # Start server in background thread
    server_thread = ServerThread(app=app, host=host, port=port)
    server_thread.start()

    # Wait for server to be ready
    base_url = f"http://{host}:{port}"
    max_retries = 50
    retry_delay = 0.1

    for _ in range(max_retries):
        try:
            import httpx
            with httpx.Client() as client:
                response = client.get(f"{base_url}/health", timeout=1.0)
                if response.status_code == 200:
                    break
        except (httpx.ConnectError, httpx.TimeoutException):
            time.sleep(retry_delay)
    else:
        raise RuntimeError(f"Server failed to start on {base_url}")

    yield base_url

    # Cleanup: stop the server thread
    server_thread.stop()


@pytest.fixture(scope="session", autouse=True)
def oauth_endpoint():
    """
    Start the OAuth mock server in a background thread.

    Yields:
        str: The base URL of the mock OAuth server (e.g., "http://127.0.0.1:29313")
    """
    yield from create_endpoint(oauth_app, "127.0.0.1", OAUTH_PORT)


@pytest.fixture(scope="session")
def app():
    port = random.randint(30000, 39999)
    yield from create_endpoint(make_app(), "127.0.0.1", port)
