#!/usr/bin/env python3

# Generated by Claude

"""

Mock Google OAuth2 server for testing.

This FastAPI server mocks Google's OAuth2 endpoints and always returns
successful authentication responses.

Run with: python tests/oauth_mock.py
Test with: curl -X POST http://localhost:8080/oauth2/token -d "grant_type=authorization_code&code=test"
"""

import json
import time
from datetime import datetime, timedelta
from typing import Optional
import base64
import uvicorn

from fastapi import FastAPI, Form, HTTPException
from fastapi.responses import JSONResponse


PORT = 29313


app = FastAPI(title="Mock Google OAuth2 Server", version="1.0.0")


def create_mock_id_token(email: str = "test@example.com", sub: str = "123456789") -> str:
    """Create a mock JWT ID token."""
    header = {"alg": "RS256", "typ": "JWT", "kid": "mock_key_id"}
    payload = {
        "iss": "https://accounts.google.com",
        "aud": "mock_client_id",
        "sub": sub,
        "email": email,
        "email_verified": True,
        "name": f"Test User {sub}",
        "given_name": "Test",
        "family_name": "User",
        "exp": int((datetime.now() + timedelta(hours=1)).timestamp()),
        "iat": int(datetime.now().timestamp()),
        "hd": "example.com"  # Hosted domain
    }
    
    header_b64 = base64.urlsafe_b64encode(
        json.dumps(header).encode()
    ).decode().rstrip('=')
    payload_b64 = base64.urlsafe_b64encode(
        json.dumps(payload).encode()
    ).decode().rstrip('=')
    
    return f"{header_b64}.{payload_b64}.mock_signature"


# Store mock tokens for refresh
mock_token_store = {}


@app.get("/.well-known/openid-configuration")
async def openid_configuration():
    """Mock OpenID Connect configuration endpoint."""
    return JSONResponse({
        "issuer": f"http://localhost:{PORT}",
        "authorization_endpoint": f"http://localhost:{PORT}/oauth2/auth",
        "token_endpoint": f"http://localhost:{PORT}/oauth2/token",
        "userinfo_endpoint": f"http://localhost:{PORT}/oauth2/userinfo",
        "jwks_uri": f"http://localhost:{PORT}/oauth2/certs",
        "response_types_supported": ["code", "token", "id_token"],
        "subject_types_supported": ["public"],
        "id_token_signing_alg_values_supported": ["RS256"],
        "scopes_supported": ["openid", "email", "profile"],
        "claims_supported": ["iss", "sub", "aud", "exp", "iat", "email", "email_verified"]
    })


@app.post("/oauth2/token")
async def token_endpoint(
    grant_type: str = Form(...),
    code: Optional[str] = Form(None),
    refresh_token: Optional[str] = Form(None),
    client_id: Optional[str] = Form(None),
    client_secret: Optional[str] = Form(None),
    redirect_uri: Optional[str] = Form(None)
):
    """Mock OAuth2 token endpoint - always returns success."""
    
    if grant_type == "authorization_code":
        # Initial token request with authorization code
        access_token = f"mock_access_token_{int(time.time())}"
        new_refresh_token = f"mock_refresh_token_{int(time.time())}"
        id_token = create_mock_id_token()
        
        # Store token data for potential refresh
        mock_token_store[new_refresh_token] = {
            "email": "test@example.com",
            "sub": "123456789",
            "access_token": access_token,
            "created_at": datetime.now()
        }
        
        return JSONResponse({
            "access_token": access_token,
            "refresh_token": new_refresh_token,
            "token_type": "Bearer",
            "expires_in": 3600,
            "id_token": id_token,
            "scope": "openid email profile"
        })
    
    elif grant_type == "refresh_token":
        # Refresh token request
        if not refresh_token:
            raise HTTPException(status_code=400, detail="refresh_token required")
        
        # Get stored user data or use defaults
        stored_data = mock_token_store.get(refresh_token, {
            "email": "test@example.com", 
            "sub": "123456789"
        })
        
        new_access_token = f"mock_access_token_refreshed_{int(time.time())}"
        new_id_token = create_mock_id_token(
            email=stored_data.get("email", "test@example.com"),
            sub=stored_data.get("sub", "123456789")
        )
        
        # Update stored data
        mock_token_store[refresh_token]["access_token"] = new_access_token
        
        return JSONResponse({
            "access_token": new_access_token,
            "token_type": "Bearer", 
            "expires_in": 3600,
            "id_token": new_id_token
        })
    
    else:
        raise HTTPException(
            status_code=400,
            detail={"error": "unsupported_grant_type", "error_description": f"Grant type '{grant_type}' not supported"}
        )


@app.get("/oauth2/userinfo")
async def userinfo_endpoint():
    """Mock OAuth2 userinfo endpoint."""
    return JSONResponse({
        "sub": "123456789",
        "email": "test@example.com", 
        "email_verified": True,
        "name": "Test User",
        "given_name": "Test",
        "family_name": "User",
        "picture": "https://example.com/avatar.jpg",
        "locale": "en",
        "hd": "example.com"
    })


@app.get("/oauth2/auth")
async def authorize_endpoint(
    client_id: str,
    redirect_uri: str,
    response_type: str = "code",
    scope: str = "openid email",
    state: Optional[str] = None
):
    """Mock OAuth2 authorization endpoint."""
    from fastapi.responses import RedirectResponse
    
    # Always approve and redirect with mock authorization code
    params = f"code=mock_auth_code_{int(time.time())}"
    if state:
        params += f"&state={state}"
    
    return RedirectResponse(url=f"{redirect_uri}?{params}")


@app.get("/oauth2/certs")
async def certs_endpoint():
    """Mock JWKS endpoint for public keys."""
    return JSONResponse({
        "keys": [
            {
                "kty": "RSA",
                "use": "sig",
                "kid": "mock_key_id",
                "n": "mock_modulus",
                "e": "AQAB",
                "alg": "RS256"
            }
        ]
    })


@app.get("/health")
async def health_check():
    """Health check endpoint."""
    return {"status": "ok", "message": "Mock OAuth2 server is running"}


@app.get("/")
async def root():
    """Root endpoint with server info."""
    return {
        "name": "Mock Google OAuth2 Server",
        "version": "1.0.0",
        "endpoints": {
            "authorization": "/oauth2/auth",
            "token": "/oauth2/token", 
            "userinfo": "/oauth2/userinfo",
            "jwks": "/oauth2/certs",
            "openid_configuration": "/.well-known/openid-configuration"
        },
        "test_commands": {
            "get_token": f"curl -X POST http://localhost:{PORT}/oauth2/token -d 'grant_type=authorization_code&code=test'",
            "refresh_token": f"curl -X POST http://localhost:{PORT}/oauth2/token -d 'grant_type=refresh_token&refresh_token=YOUR_REFRESH_TOKEN'",
            "get_userinfo": f"curl http://localhost:{PORT}/oauth2/userinfo"
        }
    }
